INCLUDE(LibFindMacros)

# Find the include directories
FIND_PATH(CYASSL_INCLUDE_DIR
    NAMES cyassl/ssl.h
    HINTS ${CYASSL_PREFIX}/include
    )

FIND_LIBRARY(CYASSL_LIBRARY
    NAMES cyassl
    HINTS ${CYASSL_PREFIX}/lib
    )

SET(CYASSL_PROCESS_INCLUDES CYASSL_INCLUDE_DIR)
SET(CYASSL_PROCESS_LIBS CYASSL_LIBRARY)

LIBFIND_PROCESS(CYASSL)
