INCLUDE(LibFindMacros)

# Find the include directories
FIND_PATH(POLARSSL_INCLUDE_DIR
    NAMES polarssl/ssl.h
    HINTS ${POLARSSL_PREFIX}/include
    )

FIND_LIBRARY(POLARSSL_LIBRARY
    NAMES polarssl
    HINTS ${POLARSSL_PREFIX}/lib
    )

SET(POLARSSL_PROCESS_INCLUDES POLARSSL_INCLUDE_DIR)
SET(POLARSSL_PROCESS_LIBS POLARSSL_LIBRARY)

LIBFIND_PROCESS(POLARSSL)
